//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor has existed in database.
        /// </summary>
        public static string DoctorExisted {
            get {
                return ResourceManager.GetString("DoctorExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is in use.
        /// </summary>
        public static string IdentityCardInUse {
            get {
                return ResourceManager.GetString("IdentityCardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status is invalid.
        /// </summary>
        public static string InvalidAccountStatus {
            get {
                return ResourceManager.GetString("InvalidAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is invalid.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is invalid.
        /// </summary>
        public static string InvalidBirthday {
            get {
                return ResourceManager.GetString("InvalidBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is incorret.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can only contains {1} character(s).
        /// </summary>
        public static string InvalidEmailMaximumLength {
            get {
                return ResourceManager.GetString("InvalidEmailMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can only contains {1} character(s).
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is invalid.
        /// </summary>
        public static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height can only be fromt {1} to {2} cm(s).
        /// </summary>
        public static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card can only contain {0} number(s).
        /// </summary>
        public static string InvalidIdentityCard {
            get {
                return ResourceManager.GetString("InvalidIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can only contains {1} characters(s).
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max birthday is invalid.
        /// </summary>
        public static string InvalidMaxBirthday {
            get {
                return ResourceManager.GetString("InvalidMaxBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max date is invalid.
        /// </summary>
        public static string InvalidMaxDate {
            get {
                return ResourceManager.GetString("InvalidMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min birthday is invalid.
        /// </summary>
        public static string InvalidMinBirthday {
            get {
                return ResourceManager.GetString("InvalidMinBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min date is invalid.
        /// </summary>
        public static string InvalidMinDate {
            get {
                return ResourceManager.GetString("InvalidMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index must be from 0.
        /// </summary>
        public static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records must be from {1} to {2}.
        /// </summary>
        public static string InvalidPageRecords {
            get {
                return ResourceManager.GetString("InvalidPageRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is invalid.
        /// </summary>
        public static string InvalidPersonalId {
            get {
                return ResourceManager.GetString("InvalidPersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can only contain numeric character(s).
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization can only contains {0} character(s).
        /// </summary>
        public static string InvalidSpecializationLength {
            get {
                return ResourceManager.GetString("InvalidSpecializationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can only be from {1} to {2} kg(s).
        /// </summary>
        public static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string RequireAddress {
            get {
                return ResourceManager.GetString("RequireAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is required.
        /// </summary>
        public static string RequireBirthday {
            get {
                return ResourceManager.GetString("RequireBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RequireEmail {
            get {
                return ResourceManager.GetString("RequireEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string RequireFirstName {
            get {
                return ResourceManager.GetString("RequireFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is required.
        /// </summary>
        public static string RequireIdentityCard {
            get {
                return ResourceManager.GetString("RequireIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string RequireLastName {
            get {
                return ResourceManager.GetString("RequireLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string RequirePersonalId {
            get {
                return ResourceManager.GetString("RequirePersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string RequirePhone {
            get {
                return ResourceManager.GetString("RequirePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization is required.
        /// </summary>
        public static string RequireSpecialization {
            get {
                return ResourceManager.GetString("RequireSpecialization", resourceCulture);
            }
        }
    }
}
