//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please access your email for account verification.
        /// </summary>
        public static string AccessEmailForVerification {
            get {
                return ResourceManager.GetString("AccessEmailForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been activated.
        /// </summary>
        public static string AccountHasBeenActivated {
            get {
                return ResourceManager.GetString("AccountHasBeenActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been disabled.
        /// </summary>
        public static string AccountHasBeenDisabled {
            get {
                return ResourceManager.GetString("AccountHasBeenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact administrators to verify this account.
        /// </summary>
        public static string DoctorAccountPending {
            get {
                return ResourceManager.GetString("DoctorAccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor doesn&apos;t exist.
        /// </summary>
        public static string DoctorDoesNotExist {
            get {
                return ResourceManager.GetString("DoctorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor has existed in database.
        /// </summary>
        public static string DoctorExisted {
            get {
                return ResourceManager.GetString("DoctorExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does exist in system..
        /// </summary>
        public static string EmailExistInSystem {
            get {
                return ResourceManager.GetString("EmailExistInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result isn&apos;t unique.
        /// </summary>
        public static string FindResultConflict {
            get {
                return ResourceManager.GetString("FindResultConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is in use.
        /// </summary>
        public static string IdentityCardInUse {
            get {
                return ResourceManager.GetString("IdentityCardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is something wrong with server. Process cannot be completed.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status is invalid.
        /// </summary>
        public static string InvalidAccountStatus {
            get {
                return ResourceManager.GetString("InvalidAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is invalid.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is invalid.
        /// </summary>
        public static string InvalidBirthday {
            get {
                return ResourceManager.GetString("InvalidBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthyear must be after {1}.
        /// </summary>
        public static string InvalidBirthyear {
            get {
                return ResourceManager.GetString("InvalidBirthyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is incorret.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can only contains {1} character(s).
        /// </summary>
        public static string InvalidEmailMaximumLength {
            get {
                return ResourceManager.GetString("InvalidEmailMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can only contains {1} character(s).
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is invalid.
        /// </summary>
        public static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height can only be fromt {1} to {2} cm(s).
        /// </summary>
        public static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card can only contains 9 numbers.
        /// </summary>
        public static string InvalidIdentityCard {
            get {
                return ResourceManager.GetString("InvalidIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date must be after year {1}.
        /// </summary>
        public static string InvalidIdentityCardIssueDate {
            get {
                return ResourceManager.GetString("InvalidIdentityCardIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue place is invalid.
        /// </summary>
        public static string InvalidIdentityCardIssuePlace {
            get {
                return ResourceManager.GetString("InvalidIdentityCardIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card can only contains {1} number(s).
        /// </summary>
        public static string InvalidIdentityCardMaxLength {
            get {
                return ResourceManager.GetString("InvalidIdentityCardMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue data is invalid.
        /// </summary>
        public static string InvalidIssueDate {
            get {
                return ResourceManager.GetString("InvalidIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can only contains {1} characters(s).
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be from {1} to {2}.
        /// </summary>
        public static string InvalidLatitude {
            get {
                return ResourceManager.GetString("InvalidLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account or password.
        /// </summary>
        public static string InvalidLoginInfo {
            get {
                return ResourceManager.GetString("InvalidLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be from {1} to {2}.
        /// </summary>
        public static string InvalidLongitude {
            get {
                return ResourceManager.GetString("InvalidLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max birthday is invalid.
        /// </summary>
        public static string InvalidMaxBirthday {
            get {
                return ResourceManager.GetString("InvalidMaxBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxCreated must be after {1}.
        /// </summary>
        public static string InvalidMaxCreated {
            get {
                return ResourceManager.GetString("InvalidMaxCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max date is invalid.
        /// </summary>
        public static string InvalidMaxDate {
            get {
                return ResourceManager.GetString("InvalidMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height should be from {1} to {2} cms(s).
        /// </summary>
        public static string InvalidMaxHeight {
            get {
                return ResourceManager.GetString("InvalidMaxHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLastModified must be after {2}.
        /// </summary>
        public static string InvalidMaxLastModified {
            get {
                return ResourceManager.GetString("InvalidMaxLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max weight should be from {1} to {2} kg(s).
        /// </summary>
        public static string InvalidMaxWeight {
            get {
                return ResourceManager.GetString("InvalidMaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min birthday is invalid.
        /// </summary>
        public static string InvalidMinBirthday {
            get {
                return ResourceManager.GetString("InvalidMinBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinCreated must be after {1}.
        /// </summary>
        public static string InvalidMinCreated {
            get {
                return ResourceManager.GetString("InvalidMinCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min date is invalid.
        /// </summary>
        public static string InvalidMinDate {
            get {
                return ResourceManager.GetString("InvalidMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min height should be from {1} to {2} cm(s).
        /// </summary>
        public static string InvalidMinHeight {
            get {
                return ResourceManager.GetString("InvalidMinHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLastModified must be after {1}.
        /// </summary>
        public static string InvalidMinLastModified {
            get {
                return ResourceManager.GetString("InvalidMinLastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min weight should be from {1} to {2} kg(s).
        /// </summary>
        public static string InvalidMinWeight {
            get {
                return ResourceManager.GetString("InvalidMinWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID is invalid.
        /// </summary>
        public static string InvalidNoteId {
            get {
                return ResourceManager.GetString("InvalidNoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index must be from 0.
        /// </summary>
        public static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records must be from {1} to {2}.
        /// </summary>
        public static string InvalidPageRecords {
            get {
                return ResourceManager.GetString("InvalidPageRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is invalid.
        /// </summary>
        public static string InvalidPatient {
            get {
                return ResourceManager.GetString("InvalidPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is invalid.
        /// </summary>
        public static string InvalidPerson {
            get {
                return ResourceManager.GetString("InvalidPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is invalid.
        /// </summary>
        public static string InvalidPersonalId {
            get {
                return ResourceManager.GetString("InvalidPersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can only contain numeric character(s).
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role should be : {1}.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality can only contains {0} character(s).
        /// </summary>
        public static string InvalidSpecializationLength {
            get {
                return ResourceManager.GetString("InvalidSpecializationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is invalid.
        /// </summary>
        public static string InvalidTemperature {
            get {
                return ResourceManager.GetString("InvalidTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can only be from {1} to {2} kg(s).
        /// </summary>
        public static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can only contain at most 16 alphanumeric characters.
        /// </summary>
        public static string MaxLengthPassword {
            get {
                return ResourceManager.GetString("MaxLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 alphanumeric characters.
        /// </summary>
        public static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be authorized to access this function.
        /// </summary>
        public static string MustAuthorize {
            get {
                return ResourceManager.GetString("MustAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please access your email to verify this account.
        /// </summary>
        public static string PatientAccountPending {
            get {
                return ResourceManager.GetString("PatientAccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not only one record has been returned.
        /// </summary>
        public static string RecordIsNotUnique {
            get {
                return ResourceManager.GetString("RecordIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can only contain alphanumeric characters.
        /// </summary>
        public static string RegexPassword {
            get {
                return ResourceManager.GetString("RegexPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are forbidden to access this function.
        /// </summary>
        public static string RequestForbidden {
            get {
                return ResourceManager.GetString("RequestForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string RequireAddress {
            get {
                return ResourceManager.GetString("RequireAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is required.
        /// </summary>
        public static string RequireBirthday {
            get {
                return ResourceManager.GetString("RequireBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RequireEmail {
            get {
                return ResourceManager.GetString("RequireEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string RequireFirstName {
            get {
                return ResourceManager.GetString("RequireFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is required.
        /// </summary>
        public static string RequireIdentityCard {
            get {
                return ResourceManager.GetString("RequireIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue place is required.
        /// </summary>
        public static string RequireIdentityCardIssuePlace {
            get {
                return ResourceManager.GetString("RequireIdentityCardIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card number is required.
        /// </summary>
        public static string RequireIdentityCardNo {
            get {
                return ResourceManager.GetString("RequireIdentityCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue date is required.
        /// </summary>
        public static string RequireIdentityIssueDate {
            get {
                return ResourceManager.GetString("RequireIdentityIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string RequireLastName {
            get {
                return ResourceManager.GetString("RequireLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string RequirePersonalId {
            get {
                return ResourceManager.GetString("RequirePersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string RequirePhone {
            get {
                return ResourceManager.GetString("RequirePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization is required.
        /// </summary>
        public static string RequireSpecialization {
            get {
                return ResourceManager.GetString("RequireSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be after {1}.
        /// </summary>
        public static string ValueMustBeAfterYear {
            get {
                return ResourceManager.GetString("ValueMustBeAfterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to or greater than {1}.
        /// </summary>
        public static string ValueMustBeEqualGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeEqualGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to or lower than {1}.
        /// </summary>
        public static string ValueMustBeEqualLowerThan {
            get {
                return ResourceManager.GetString("ValueMustBeEqualLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string ValueMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for admin confirmation.
        /// </summary>
        public static string WaitForAdminConfirmation {
            get {
                return ResourceManager.GetString("WaitForAdminConfirmation", resourceCulture);
            }
        }
    }
}
