//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please access your email for account verification.
        /// </summary>
        public static string AccessEmailForVerification {
            get {
                return ResourceManager.GetString("AccessEmailForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been activated.
        /// </summary>
        public static string AccountHasBeenActivated {
            get {
                return ResourceManager.GetString("AccountHasBeenActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been disabled.
        /// </summary>
        public static string AccountHasBeenDisabled {
            get {
                return ResourceManager.GetString("AccountHasBeenDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor doesn&apos;t exist.
        /// </summary>
        public static string DoctorDoesNotExist {
            get {
                return ResourceManager.GetString("DoctorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor has existed in database.
        /// </summary>
        public static string DoctorExisted {
            get {
                return ResourceManager.GetString("DoctorExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result isn&apos;t unique.
        /// </summary>
        public static string FindResultConflict {
            get {
                return ResourceManager.GetString("FindResultConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is in use.
        /// </summary>
        public static string IdentityCardInUse {
            get {
                return ResourceManager.GetString("IdentityCardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account status is invalid.
        /// </summary>
        public static string InvalidAccountStatus {
            get {
                return ResourceManager.GetString("InvalidAccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code is invalid.
        /// </summary>
        public static string InvalidActivationCode {
            get {
                return ResourceManager.GetString("InvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is invalid.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is invalid.
        /// </summary>
        public static string InvalidBirthday {
            get {
                return ResourceManager.GetString("InvalidBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthyear must be after {1}.
        /// </summary>
        public static string InvalidBirthyear {
            get {
                return ResourceManager.GetString("InvalidBirthyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is incorret.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can only contains {1} character(s).
        /// </summary>
        public static string InvalidEmailMaximumLength {
            get {
                return ResourceManager.GetString("InvalidEmailMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name can only contains {1} character(s).
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is invalid.
        /// </summary>
        public static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height can only be fromt {1} to {2} cm(s).
        /// </summary>
        public static string InvalidHeight {
            get {
                return ResourceManager.GetString("InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card can only contains 9 numbers.
        /// </summary>
        public static string InvalidIdentityCard {
            get {
                return ResourceManager.GetString("InvalidIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue date must be after year {1}.
        /// </summary>
        public static string InvalidIdentityCardIssueDate {
            get {
                return ResourceManager.GetString("InvalidIdentityCardIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue place is invalid.
        /// </summary>
        public static string InvalidIdentityCardIssuePlace {
            get {
                return ResourceManager.GetString("InvalidIdentityCardIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card can only contains {1} number(s).
        /// </summary>
        public static string InvalidIdentityCardMaxLength {
            get {
                return ResourceManager.GetString("InvalidIdentityCardMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue data is invalid.
        /// </summary>
        public static string InvalidIssueDate {
            get {
                return ResourceManager.GetString("InvalidIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name can only contains {1} characters(s).
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid account or password.
        /// </summary>
        public static string InvalidLoginInfo {
            get {
                return ResourceManager.GetString("InvalidLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max birthday is invalid.
        /// </summary>
        public static string InvalidMaxBirthday {
            get {
                return ResourceManager.GetString("InvalidMaxBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max date is invalid.
        /// </summary>
        public static string InvalidMaxDate {
            get {
                return ResourceManager.GetString("InvalidMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID is invalid.
        /// </summary>
        public static string InvalidNoteId {
            get {
                return ResourceManager.GetString("InvalidNoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient is invalid.
        /// </summary>
        public static string InvalidPatient {
            get {
                return ResourceManager.GetString("InvalidPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is invalid.
        /// </summary>
        public static string InvalidPerson {
            get {
                return ResourceManager.GetString("InvalidPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is invalid.
        /// </summary>
        public static string InvalidPersonalId {
            get {
                return ResourceManager.GetString("InvalidPersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number can only contain numeric character(s).
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request parameters are invalid.
        /// </summary>
        public static string InvalidRequestParameters {
            get {
                return ResourceManager.GetString("InvalidRequestParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role should be : {1}.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality can only contains {0} character(s).
        /// </summary>
        public static string InvalidSpecializationLength {
            get {
                return ResourceManager.GetString("InvalidSpecializationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature is invalid.
        /// </summary>
        public static string InvalidTemperature {
            get {
                return ResourceManager.GetString("InvalidTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight can only be from {1} to {2} kg(s).
        /// </summary>
        public static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login information is conflicted.
        /// </summary>
        public static string LoginConflict {
            get {
                return ResourceManager.GetString("LoginConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can only contain at most 16 alphanumeric characters.
        /// </summary>
        public static string MaxLengthPassword {
            get {
                return ResourceManager.GetString("MaxLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Olives Health. Your account has been activated successfully..
        /// </summary>
        public static string MessageAccountActivatedSuccessfully {
            get {
                return ResourceManager.GetString("MessageAccountActivatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code is invalid.
        /// </summary>
        public static string MessageInvalidActivationCode {
            get {
                return ResourceManager.GetString("MessageInvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 alphanumeric characters.
        /// </summary>
        public static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be authorized to access this function.
        /// </summary>
        public static string MustAuthorize {
            get {
                return ResourceManager.GetString("MustAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive account activation code.
        /// </summary>
        public static string OliveActivationCodeEmailTitle {
            get {
                return ResourceManager.GetString("OliveActivationCodeEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please access your email to verify this account.
        /// </summary>
        public static string PatientAccountPending {
            get {
                return ResourceManager.GetString("PatientAccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not only one record has been returned.
        /// </summary>
        public static string RecordIsNotUnique {
            get {
                return ResourceManager.GetString("RecordIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can only contain alphanumeric characters.
        /// </summary>
        public static string RegexPassword {
            get {
                return ResourceManager.GetString("RegexPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are forbidden to access this function.
        /// </summary>
        public static string RequestForbidden {
            get {
                return ResourceManager.GetString("RequestForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string RequireAddress {
            get {
                return ResourceManager.GetString("RequireAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday is required.
        /// </summary>
        public static string RequireBirthday {
            get {
                return ResourceManager.GetString("RequireBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RequireEmail {
            get {
                return ResourceManager.GetString("RequireEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string RequireFirstName {
            get {
                return ResourceManager.GetString("RequireFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card is required.
        /// </summary>
        public static string RequireIdentityCard {
            get {
                return ResourceManager.GetString("RequireIdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue place is required.
        /// </summary>
        public static string RequireIdentityCardIssuePlace {
            get {
                return ResourceManager.GetString("RequireIdentityCardIssuePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card number is required.
        /// </summary>
        public static string RequireIdentityCardNo {
            get {
                return ResourceManager.GetString("RequireIdentityCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity card issue date is required.
        /// </summary>
        public static string RequireIdentityIssueDate {
            get {
                return ResourceManager.GetString("RequireIdentityIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string RequireLastName {
            get {
                return ResourceManager.GetString("RequireLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id is required.
        /// </summary>
        public static string RequirePersonalId {
            get {
                return ResourceManager.GetString("RequirePersonalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string RequirePhone {
            get {
                return ResourceManager.GetString("RequirePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization is required.
        /// </summary>
        public static string RequireSpecialization {
            get {
                return ResourceManager.GetString("RequireSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only {1} character(s).
        /// </summary>
        public static string ValueCanOnlyContainCharacter {
            get {
                return ResourceManager.GetString("ValueCanOnlyContainCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string ValueIsInvalid {
            get {
                return ResourceManager.GetString("ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be after {1}.
        /// </summary>
        public static string ValueMustBeAfterYear {
            get {
                return ResourceManager.GetString("ValueMustBeAfterYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to or greater than {1}.
        /// </summary>
        public static string ValueMustBeEqualGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeEqualGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to or lower than {1}.
        /// </summary>
        public static string ValueMustBeEqualLowerThan {
            get {
                return ResourceManager.GetString("ValueMustBeEqualLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be from {1} to {2}.
        /// </summary>
        public static string ValueMustBeFromTo {
            get {
                return ResourceManager.GetString("ValueMustBeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string ValueMustBeGreaterThan {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in the list {1}.
        /// </summary>
        public static string ValueMustBeOneOfArray {
            get {
                return ResourceManager.GetString("ValueMustBeOneOfArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for admin confirmation.
        /// </summary>
        public static string WaitForAdminConfirmation {
            get {
                return ResourceManager.GetString("WaitForAdminConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W014.
        /// </summary>
        public static string WarnAccountAlreadyExists {
            get {
                return ResourceManager.GetString("WarnAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W012.
        /// </summary>
        public static string WarnAccountNotLogin {
            get {
                return ResourceManager.GetString("WarnAccountNotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W018.
        /// </summary>
        public static string WarnCountryNotFound {
            get {
                return ResourceManager.GetString("WarnCountryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W009.
        /// </summary>
        public static string WarnDaterInvalidRole {
            get {
                return ResourceManager.GetString("WarnDaterInvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W008.
        /// </summary>
        public static string WarnDaterNotFound {
            get {
                return ResourceManager.GetString("WarnDaterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W010.
        /// </summary>
        public static string WarnDaterNotSelf {
            get {
                return ResourceManager.GetString("WarnDaterNotSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W011.
        /// </summary>
        public static string WarnDaterSameRole {
            get {
                return ResourceManager.GetString("WarnDaterSameRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W002.
        /// </summary>
        public static string WarnDisabledAccount {
            get {
                return ResourceManager.GetString("WarnDisabledAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W026.
        /// </summary>
        public static string WarnFailedBulkUpdate {
            get {
                return ResourceManager.GetString("WarnFailedBulkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W013.
        /// </summary>
        public static string WarnForbiddenAccessMethod {
            get {
                return ResourceManager.GetString("WarnForbiddenAccessMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W019.
        /// </summary>
        public static string WarnHasNoRelationship {
            get {
                return ResourceManager.GetString("WarnHasNoRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W020.
        /// </summary>
        public static string WarnImageIncorrectFormat {
            get {
                return ResourceManager.GetString("WarnImageIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W021.
        /// </summary>
        public static string WarnInternalServerError {
            get {
                return ResourceManager.GetString("WarnInternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W003.
        /// </summary>
        public static string WarnMedicalRecordNotFound {
            get {
                return ResourceManager.GetString("WarnMedicalRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W004.
        /// </summary>
        public static string WarnNotAuthorizedAccount {
            get {
                return ResourceManager.GetString("WarnNotAuthorizedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W023.
        /// </summary>
        public static string WarnOwnerNotActive {
            get {
                return ResourceManager.GetString("WarnOwnerNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W001.
        /// </summary>
        public static string WarnPendingAccount {
            get {
                return ResourceManager.GetString("WarnPendingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W025.
        /// </summary>
        public static string WarnPrescriptionExpired {
            get {
                return ResourceManager.GetString("WarnPrescriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W024.
        /// </summary>
        public static string WarnPrescriptionNotFound {
            get {
                return ResourceManager.GetString("WarnPrescriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W005.
        /// </summary>
        public static string WarnRecordConflict {
            get {
                return ResourceManager.GetString("WarnRecordConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W006.
        /// </summary>
        public static string WarnRecordNotFound {
            get {
                return ResourceManager.GetString("WarnRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W007.
        /// </summary>
        public static string WarnRelationNotExist {
            get {
                return ResourceManager.GetString("WarnRelationNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W017.
        /// </summary>
        public static string WarnRelationNotFound {
            get {
                return ResourceManager.GetString("WarnRelationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W016.
        /// </summary>
        public static string WarnRelationshipAlreadyExist {
            get {
                return ResourceManager.GetString("WarnRelationshipAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W022.
        /// </summary>
        public static string WarnRoleIsForbidden {
            get {
                return ResourceManager.GetString("WarnRoleIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W015.
        /// </summary>
        public static string WarnTargetAccountNotFound {
            get {
                return ResourceManager.GetString("WarnTargetAccountNotFound", resourceCulture);
            }
        }
    }
}
