//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountToken
    {
        public int Owner { get; set; }
        public string Code { get; set; }
        public byte Type { get; set; }
        public System.DateTime Expired { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
