//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentNotification
    {
        public int Id { get; set; }
        public byte Type { get; set; }
        public int Invoker { get; set; }
        public int Recipient { get; set; }
        public double Created { get; set; }
        public int AppointmentId { get; set; }
        public bool IsSeen { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
