//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int Id { get; set; }
        public Nullable<double> Rank { get; set; }
        public int SpecialtyId { get; set; }
        public string SpecialtyName { get; set; }
        public int Voters { get; set; }
        public int Money { get; set; }
        public int CityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Person Person { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
