//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExperimentNote()
        {
            this.ExperimentInfoes = new HashSet<ExperimentInfo>();
        }
    
        public int Id { get; set; }
        public int MedicalRecordId { get; set; }
        public int Owner { get; set; }
        public double Created { get; set; }
        public Nullable<double> LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExperimentInfo> ExperimentInfoes { get; set; }
        public virtual MedicalRecord MedicalRecord { get; set; }
        public virtual Person Person { get; set; }
    }
}
