//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentInfo
    {
        public int ExperimentId { get; set; }
        public string Key { get; set; }
        public double Value { get; set; }
    
        public virtual ExperimentNote ExperimentNote { get; set; }
    }
}
