//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalRecord()
        {
            this.MedicalImages = new HashSet<MedicalImage>();
        }
    
        public int Id { get; set; }
        public int Owner { get; set; }
        public string Summary { get; set; }
        public string Tests { get; set; }
        public string AdditionalMorbidities { get; set; }
        public string DifferentialDiagnosis { get; set; }
        public string OtherPathologies { get; set; }
        public double Time { get; set; }
        public double Created { get; set; }
        public Nullable<double> LastModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalImage> MedicalImages { get; set; }
        public virtual Person Person { get; set; }
    }
}
