//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptedMedicine
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public int Owner { get; set; }
        public string MedicineName { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
        public double Expired { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
