//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionImage
    {
        public int Id { get; set; }
        public int PrescriptionId { get; set; }
        public int MedicalRecordId { get; set; }
        public string Image { get; set; }
        public string FullPath { get; set; }
        public int Owner { get; set; }
        public int Creator { get; set; }
        public double Created { get; set; }
        public bool Available { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Person Person { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
