//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCheckAppointment
    {
        public int AppointmentId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime StartTime { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
